string='''0:00~Start
0:03~Tik Tok (Kesha)
0:17~Break Your Heart (Taio Cruz)
0:25~California Gurls (Katy Perry)
0:36~Love The Way You Lie (Eminem ft. Rihanna)
0:47~Teenage Dream (Katy Perry)
0:56~Like A G6 (Far East Movement ft. The Cataracts And Dev) 
1:05~Only Girl (Rihanna)
1:12~Raise Your Glass (Pink)
1:24~Firework (Katy Perry)
1:33~Grenade (Bruno Mars)
1:41~Black And Yellow (Wiz Khalifa)
1:43~Born This Way (Lady Gaga)
1:51~Rolling In The Deep (Adele)
2:01~Give Me Everything (Pitbull ft. Ne-Yo, Afrojack, Nayer)
2:10~Party Rock Anthem (LMFAO ft. Lauren Bennett, GoonRock)
2:17~Last Friday Night T.G.I.F. (Katy Perry)
2:26~Moves Like Jagger (Maroon 5  ft. Christina Aguilera)
2:34~Someone Like You (Adele)
2:47~We Found Love (Rihanna ft. Calvin Harris)
2:55~Part Of Me (Katy Perry)
3:02~We Are Young (Fun ft. Janelle Monae)
3:14~Somebody That I Used To Know (Gotye ft. Kimbra)
3:21~Call Me Maybe (Carly Rae Jepsen)
3:28~We Are Never Ever Getting Back Together (Taylor Swift)
3:40~One More Night (Maroon 5)
3:50~Diamonds (Rihanna)
3:58~Locked Out Of Heaven (Bruno Mars)
4:08~Thrift Shop (Macklemore and Ryan Lewis ft. Wanz)
4:17~Harlem Shake (Baauer)
4:23~When I Was Your Man (Bruno Mars)
4:36~Just Give Me A Reason (Pink ft. Nate Ruess)
4:44~Cant Hold Us (Macklemore and Ryan Lewis ft. Ray Dalton)
4:55~Blurred Lines (Robin Thicke ft. T.i., Pharrell)
5:00~Roar (Katy Perry)
5:10~Wrecking Ball (Miley Cyrus)
5:22~Royals (Lorde)
5:30~The Monster (Eminem ft. Rihanna)
5:40~Timber (Pitbull ft. Kesha)
5:47~Dark Horse (Katy Perry ft. Juicy J)
5:55~Happy (Pharrell Williams)
6:07~All Of Me (John Legend)
6:14~Fancy (Iggy Azalea ft. Charli XCX)
6:24~Rude (Magic!)
6:30~Shake It Off (Taylor Swift)
6:42~All About That Bass (Meghan Trainor)
6:43~Uptown Funk (Mark Ronson ft. Bruno Mars)
6:52~See You Again (Wiz Khalifa ft. Charlie Puth)
7:04~Cheerleader (Omi)
7:11~Cant Feel My Face (The Weeknd)
7:19~What Do You Mean (Justin Bieber)
7:26~The Hills (The Weeknd)
7:36~Hello (Adele)
7:49~Sorry (Justin Bieber)
7:59~Love Yourself (Justin Bieber)
8:07~Work (Rihanna ft. Drake)
8:16~Panda (Desiigner)
8:22~One Dance (Drake ft. WizKid, Kyla)
8:29~Cant Stop The Feeling! (Justin Timberlake)
8:35~Closer (The Chainsmokers ft. Halsey)
8:47~Black Beatles (Rae Sremmurd  ft. Gucci Mane)
8:55~Starboy (The Weeknd ft. Daft Punk)
9:06~Humble (Kendrick Lamar)
9:11~Thats What I Like (Bruno Mars)
9:19~I'm The One (DJ Khaled ft. Justin Bieber, Quavo, Chance The Rapper, and Lil Wayne)
9:27~Despacito (Luis Fonsi and Daddy Yankee ft. Justin Bieber)
9:37~Look What You Made Me Do (Taylor Swift)
9:41~Bodak Yellow (Cardi B)
9:49~Rockstar (Post Malone ft. 21 Savage)
9:58~Perfect (Ed Sheeran)
10:10~Havana (Camila Cabello ft. Young Thug)
10:16~God's Plan (Drake)
10:22~Nice For What (Drake)
10:27~This Is America (Childish Gambino)
10:35~Psycho (Post Malone ft. Ty Dolla Sign)
10:42~Sad! (XXXTentacion)
10:48~I Like It (Cardi B, Bad Bunny and J Balvin)
10:56~In My Feelings (Drake)
11:07~Girls Like You (Maroon 5 ft. Cardi B)
11:16~Thank u, next (Ariana Grande)
11:28~Without Me (Halsey)
11:35~Sunflower (Post Malone, Swae Lee)
11:46~7 Rings (Ariana Grande)
11:52~Sucker (Jonas Brothers)
12:00~Old Town Road (Lil Nas X)
12:15~Bad Guy (Billie Eilish)
12:27~Señorita (Shawn Mendes, Camila Cabello)
12:34~Truth Hurts (Lizzo)
12:45~Someone You Loved (Lewis Capaldi)
12:56~Lose You To Love Me (Selena Gomez)'''
lst = string.split('\n')
newlst = []
for item in lst:
    newlst.append(item[item.find('~')+1:])
print(*newlst)
newtext = ""
for item in newlst:
    newtext+= "!p " + item + "\n"
print(newtext)